apiVersion: { version }
kind: ServiceAccount
metadata:
  name: { what the service account is called that you want to add }
  namespace: { where the namespace lives }
  # if using a CI/CD tool you can add these labels
  labels:
    app.kubernetes.io/managed-by: argocd
